-- Esquema Backlogística: IDs de catálogo y transaccionales en integer.
-- Usuarios: `id_usuario` integer (IDENTITY) + `auth_user_id` uuid (Supabase Auth `sub`).
-- Pedidos / factura / usuario_rol referencian `usuarios.id_usuario` (entero).

CREATE TABLE public.rol (
  id_rol integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rol_nombre_unique UNIQUE (nombre)
);

CREATE TABLE public.tipo_documento (
  id_tipo_documento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  abreviacion varchar(16) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tipo_documento_nombre_unique UNIQUE (nombre)
);

CREATE TABLE public.pais (
  id_pais integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  codigo_dane varchar(16) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pais_codigo_dane_unique UNIQUE (codigo_dane)
);

CREATE TABLE public.departamento (
  id_departamento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  codigo_dane varchar(16) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT departamento_codigo_dane_unique UNIQUE (codigo_dane)
);

CREATE TABLE public.ciudad (
  id_ciudad integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  codigo_dane varchar(16) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ciudad_codigo_dane_unique UNIQUE (codigo_dane)
);

CREATE TABLE public.zona_bogota (
  id_zona integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT zona_bogota_nombre_unique UNIQUE (nombre)
);

-- Parámetros de negocio (antes en .env). `clave` única; `valor` según `tipo`.
CREATE TABLE public.variable (
  id_variable integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave varchar(120) NOT NULL,
  valor text NOT NULL,
  tipo varchar(32) NOT NULL DEFAULT 'text',
  descripcion text,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT variable_clave_unique UNIQUE (clave)
);

CREATE TABLE public.tipo_via (
  id_tipo_via integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tipo_via_nombre_unique UNIQUE (nombre)
);

CREATE TABLE public.estado_pedido (
  id_estado_pedido integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT estado_pedido_nombre_unique UNIQUE (nombre)
);

CREATE TABLE public.tipo_pedido (
  id_tipo_pedido integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tipo_pedido_nombre_unique UNIQUE (nombre)
);

CREATE TABLE public.metodo_recepcion (
  id_metodo_recepcion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT metodo_recepcion_nombre_unique UNIQUE (nombre)
);

CREATE TABLE public.metodo_pago (
  id_metodo_pago integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(80) NOT NULL,
  codigo varchar(32) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT metodo_pago_codigo_unique UNIQUE (codigo)
);

CREATE TABLE public.resultado_entrega (
  id_resultado_entrega integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(80) NOT NULL,
  codigo varchar(32) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT resultado_entrega_codigo_unique UNIQUE (codigo)
);

-- ---------------------------------------------------------------------------
-- Usuarios (id entero; Auth en auth_user_id)
-- ---------------------------------------------------------------------------
CREATE TABLE public.usuarios (
  id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id uuid NOT NULL,
  nombres varchar(120) NOT NULL,
  apellidos varchar(120) NOT NULL,
  fk_tipo_documento integer NOT NULL REFERENCES public.tipo_documento (id_tipo_documento),
  documento varchar(32) NOT NULL,
  correo varchar(254) NOT NULL,
  telefono varchar(32) NOT NULL,
  capacidad_max_pedidos integer,
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT usuarios_correo_unique UNIQUE (correo),
  CONSTRAINT usuarios_auth_user_id_unique UNIQUE (auth_user_id)
);

CREATE TABLE public.usuario_rol (
  id_usuario integer NOT NULL REFERENCES public.usuarios (id_usuario) ON DELETE CASCADE,
  id_rol integer NOT NULL REFERENCES public.rol (id_rol) ON DELETE CASCADE,
  PRIMARY KEY (id_usuario, id_rol)
);

-- ---------------------------------------------------------------------------
-- Transaccionales
-- ---------------------------------------------------------------------------
CREATE TABLE public.destinatario (
  id_destinatario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(200) NOT NULL,
  telefono varchar(32) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.paquete (
  id_paquete integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(200) NOT NULL,
  peso double precision NOT NULL,
  precio numeric(14, 4) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.direccion (
  id_direccion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_tipo_via integer NOT NULL REFERENCES public.tipo_via (id_tipo_via),
  fk_pais integer NOT NULL REFERENCES public.pais (id_pais),
  fk_departamento integer NOT NULL REFERENCES public.departamento (id_departamento),
  fk_ciudad integer NOT NULL REFERENCES public.ciudad (id_ciudad),
  fk_zona integer REFERENCES public.zona_bogota (id_zona),
  zona text NOT NULL,
  numero_principal text NOT NULL,
  numero_secundario text NOT NULL,
  observaciones text,
  latitud numeric,
  longitud numeric,
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.pedidos (
  id_pedido integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  num_guia varchar(64) NOT NULL,
  fk_tipo_pedido integer NOT NULL REFERENCES public.tipo_pedido (id_tipo_pedido),
  fk_usuario_solicitud integer NOT NULL REFERENCES public.usuarios (id_usuario),
  fk_usuario_recolector integer REFERENCES public.usuarios (id_usuario),
  fk_usuario_repartidor integer REFERENCES public.usuarios (id_usuario),
  fk_metodo_recepcion integer NOT NULL REFERENCES public.metodo_recepcion (id_metodo_recepcion),
  fk_paquete integer NOT NULL REFERENCES public.paquete (id_paquete),
  fk_direccion integer NOT NULL REFERENCES public.direccion (id_direccion),
  fk_estado_pedido integer NOT NULL REFERENCES public.estado_pedido (id_estado_pedido),
  fk_destinatario integer REFERENCES public.destinatario (id_destinatario),
  precio numeric(14, 4) NOT NULL,
  valor_declarado numeric(14, 4) NOT NULL,
  fecha_entrega date NOT NULL,
  es_fragil boolean NOT NULL DEFAULT false,
  pagado_por_remitente boolean,
  valor_recaudado numeric(14, 4),
  fk_metodo_pago integer REFERENCES public.metodo_pago (id_metodo_pago),
  creado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pedidos_num_guia_unique UNIQUE (num_guia)
);

CREATE TABLE public.seguimiento (
  id_seguimiento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_pedido integer NOT NULL REFERENCES public.pedidos (id_pedido) ON DELETE CASCADE,
  fk_estado integer NOT NULL REFERENCES public.estado_pedido (id_estado_pedido),
  fecha timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_seguimiento_fk_pedido ON public.seguimiento (fk_pedido);

CREATE TABLE public.descripcion_seguimiento (
  id_descripcion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_seguimiento integer NOT NULL REFERENCES public.seguimiento (id_seguimiento) ON DELETE CASCADE,
  fk_estado integer NOT NULL REFERENCES public.estado_pedido (id_estado_pedido),
  fk_resultado_entrega integer REFERENCES public.resultado_entrega (id_resultado_entrega),
  descripcion text,
  foto_url text,
  observaciones text,
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_descripcion_seguimiento_fk_seguimiento
  ON public.descripcion_seguimiento (fk_seguimiento);

-- ---------------------------------------------------------------------------
-- Facturación
-- ---------------------------------------------------------------------------
CREATE TABLE public.estado_factura (
  id_estado_factura integer PRIMARY KEY,
  nombre varchar(80) NOT NULL UNIQUE
);

CREATE TABLE public.factura (
  id_factura integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero varchar(32) NOT NULL,
  fk_cliente integer NOT NULL REFERENCES public.usuarios (id_usuario),
  fk_pedido integer NOT NULL UNIQUE REFERENCES public.pedidos (id_pedido) ON DELETE CASCADE,
  fk_estado_factura integer NOT NULL REFERENCES public.estado_factura (id_estado_factura),
  monto numeric(14, 4) NOT NULL,
  monto_cobrado numeric(14, 4) NOT NULL DEFAULT 0,
  pagado_al_crear boolean NOT NULL DEFAULT false,
  fecha_pago timestamptz,
  fecha_cierre timestamptz,
  fk_metodo_pago integer REFERENCES public.metodo_pago (id_metodo_pago),
  destinatario_nombre varchar(200) NOT NULL,
  destinatario_telefono varchar(32) NOT NULL,
  direccion_entrega text NOT NULL,
  fk_destinatario integer REFERENCES public.destinatario (id_destinatario) ON DELETE SET NULL,
  fk_direccion integer REFERENCES public.direccion (id_direccion) ON DELETE SET NULL,
  observaciones text,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT factura_numero_unique UNIQUE (numero),
  CONSTRAINT factura_monto_nonneg CHECK (monto >= 0),
  CONSTRAINT factura_monto_cobrado_nonneg CHECK (monto_cobrado >= 0)
);

CREATE INDEX idx_factura_fk_cliente ON public.factura (fk_cliente);
CREATE INDEX idx_factura_fk_estado ON public.factura (fk_estado_factura);
