-- Dispersión de pagos a repartidores + meta diaria KPI.
-- Ejecutar en Supabase después de 17-seed-finanzas-variables.sql.

CREATE TABLE IF NOT EXISTS public.dispersion_lote (
  id_dispersion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monto_total numeric(14, 4) NOT NULL,
  entregas_total integer NOT NULL,
  repartidores_total integer NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dispersion_detalle (
  id_dispersion integer NOT NULL REFERENCES public.dispersion_lote (id_dispersion) ON DELETE CASCADE,
  fk_pedido integer NOT NULL UNIQUE REFERENCES public.pedidos (id_pedido),
  fk_usuario_repartidor integer NOT NULL REFERENCES public.usuarios (id_usuario),
  monto numeric(14, 4) NOT NULL,
  PRIMARY KEY (id_dispersion, fk_pedido)
);

CREATE INDEX IF NOT EXISTS idx_dispersion_detalle_repartidor
  ON public.dispersion_detalle (fk_usuario_repartidor);

INSERT INTO public.variable (clave, valor, tipo, descripcion) VALUES
  (
    'FINANZAS_META_ENTREGAS_DIARIA',
    '2500',
    'integer',
    'Meta de entregas diarias para KPI Entregas hoy (dashboard Pago a Repartidores).'
  )
ON CONFLICT (clave) DO UPDATE SET
  valor = EXCLUDED.valor,
  tipo = EXCLUDED.tipo,
  descripcion = EXCLUDED.descripcion,
  actualizado_en = now();
