-- =============================================================================
-- FACTURACIÓN — ejecutar completo en Supabase SQL Editor (una sola vez).
-- Requiere tablas existentes: usuarios, pedidos, metodo_pago, destinatario, direccion.
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1) Catálogo estado_factura
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.estado_factura (
  id_estado_factura integer PRIMARY KEY,
  nombre varchar(80) NOT NULL UNIQUE
);

COMMENT ON TABLE public.estado_factura IS 'Estados de la factura: Creada, Pagada, Por cobrar, Saldo a favor.';

INSERT INTO public.estado_factura (id_estado_factura, nombre) VALUES
  (1, 'Creada'),
  (2, 'Pagada'),
  (3, 'Por cobrar'),
  (4, 'Saldo a favor')
ON CONFLICT (id_estado_factura) DO UPDATE SET nombre = EXCLUDED.nombre;

-- ---------------------------------------------------------------------------
-- 2) Tabla factura (crear si no existe)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.factura (
  id_factura integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero varchar(32) NOT NULL,
  fk_cliente integer NOT NULL,
  fk_pedido integer NOT NULL,
  fk_estado_factura integer NOT NULL,
  monto numeric(14, 4) NOT NULL,
  monto_cobrado numeric(14, 4) NOT NULL DEFAULT 0,
  pagado_al_crear boolean NOT NULL DEFAULT false,
  fecha_pago timestamptz,
  fecha_cierre timestamptz,
  fk_metodo_pago integer,
  destinatario_nombre varchar(200) NOT NULL,
  destinatario_telefono varchar(32) NOT NULL,
  direccion_entrega text NOT NULL,
  fk_destinatario integer,
  fk_direccion integer,
  observaciones text,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT factura_numero_unique UNIQUE (numero),
  CONSTRAINT factura_monto_nonneg CHECK (monto >= 0),
  CONSTRAINT factura_monto_cobrado_nonneg CHECK (monto_cobrado >= 0)
);

COMMENT ON TABLE public.factura IS 'Una factura por pedido; se crea al alta del pedido y se cierra al finalizar (Entregado/Cancelado/No entregado).';
COMMENT ON COLUMN public.factura.fk_cliente IS 'Cliente facturado → usuarios.id_usuario (solicitante del pedido).';
COMMENT ON COLUMN public.factura.fk_pedido IS 'Pedido origen (1:1) → pedidos.id_pedido.';
COMMENT ON COLUMN public.factura.fk_estado_factura IS 'Estado actual → estado_factura.id_estado_factura.';
COMMENT ON COLUMN public.factura.pagado_al_crear IS 'true si el remitente pagó al crear el despacho (prepago).';
COMMENT ON COLUMN public.factura.fecha_cierre IS 'Cuándo el pedido pasó a estado terminal y se cerró la factura.';

-- ---------------------------------------------------------------------------
-- 3) Columnas nuevas (si venías del esquema antiguo con esta_paga)
-- ---------------------------------------------------------------------------
ALTER TABLE public.factura ADD COLUMN IF NOT EXISTS fk_estado_factura integer;
ALTER TABLE public.factura ADD COLUMN IF NOT EXISTS monto_cobrado numeric(14, 4) NOT NULL DEFAULT 0;
ALTER TABLE public.factura ADD COLUMN IF NOT EXISTS pagado_al_crear boolean NOT NULL DEFAULT false;
ALTER TABLE public.factura ADD COLUMN IF NOT EXISTS fecha_cierre timestamptz;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'factura' AND column_name = 'esta_paga'
  ) THEN
    UPDATE public.factura
    SET fk_estado_factura = CASE WHEN esta_paga THEN 2 ELSE 1 END,
        monto_cobrado = CASE WHEN esta_paga THEN monto ELSE 0 END
    WHERE fk_estado_factura IS NULL;

    ALTER TABLE public.factura DROP COLUMN IF EXISTS esta_paga;
  END IF;
END $$;

UPDATE public.factura SET fk_estado_factura = 1 WHERE fk_estado_factura IS NULL;

ALTER TABLE public.factura
  ALTER COLUMN fk_estado_factura SET NOT NULL;

-- ---------------------------------------------------------------------------
-- 4a) Relación factura → estado_factura (ALTER explícito)
--     También disponible solo en: database/factura-alter-fk-estado-factura.sql
-- ---------------------------------------------------------------------------
ALTER TABLE public.factura
  DROP CONSTRAINT IF EXISTS factura_fk_estado_factura_fkey;

ALTER TABLE public.factura
  DROP CONSTRAINT IF EXISTS factura_fk_estado_fkey;

ALTER TABLE public.factura
  ADD CONSTRAINT factura_fk_estado_factura_fkey
  FOREIGN KEY (fk_estado_factura)
  REFERENCES public.estado_factura (id_estado_factura);

-- ---------------------------------------------------------------------------
-- 4b) Resto de relaciones (FK) — idempotente
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'factura_fk_cliente_fkey') THEN
    ALTER TABLE public.factura
      ADD CONSTRAINT factura_fk_cliente_fkey
      FOREIGN KEY (fk_cliente) REFERENCES public.usuarios (id_usuario);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'factura_fk_pedido_fkey') THEN
    ALTER TABLE public.factura
      ADD CONSTRAINT factura_fk_pedido_fkey
      FOREIGN KEY (fk_pedido) REFERENCES public.pedidos (id_pedido) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'factura_fk_metodo_pago_fkey') THEN
    ALTER TABLE public.factura
      ADD CONSTRAINT factura_fk_metodo_pago_fkey
      FOREIGN KEY (fk_metodo_pago) REFERENCES public.metodo_pago (id_metodo_pago);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'factura_fk_destinatario_fkey') THEN
    ALTER TABLE public.factura
      ADD CONSTRAINT factura_fk_destinatario_fkey
      FOREIGN KEY (fk_destinatario) REFERENCES public.destinatario (id_destinatario) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'factura_fk_direccion_fkey') THEN
    ALTER TABLE public.factura
      ADD CONSTRAINT factura_fk_direccion_fkey
      FOREIGN KEY (fk_direccion) REFERENCES public.direccion (id_direccion) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'factura_fk_pedido_unique') THEN
    ALTER TABLE public.factura
      ADD CONSTRAINT factura_fk_pedido_unique UNIQUE (fk_pedido);
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 5) Índices
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_factura_fk_cliente ON public.factura (fk_cliente);
CREATE INDEX IF NOT EXISTS idx_factura_fk_estado ON public.factura (fk_estado_factura);
CREATE UNIQUE INDEX IF NOT EXISTS idx_factura_fk_pedido ON public.factura (fk_pedido);

COMMIT;

-- Verificación
SELECT 'estado_factura' AS tabla, count(*) AS filas FROM public.estado_factura
UNION ALL
SELECT 'factura', count(*) FROM public.factura;
