-- Instalación de facturación en BD existente.
-- En Supabase SQL Editor ejecute: database/patch-factura-columnas-nuevas.sql
-- (si ya tiene tabla factura antigua) o database/factura-install.sql (instalación completa).
