-- Facturación en BD existente (sin recrear todo el esquema).
-- Si ya usó `01-schema-numeric-ids.sql` reciente, no hace falta.

CREATE TABLE IF NOT EXISTS public.factura (
  id_factura integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero varchar(32) NOT NULL,
  fk_cliente uuid NOT NULL REFERENCES public.usuarios (id_usuario),
  fk_pedido integer REFERENCES public.pedidos (id_pedido) ON DELETE SET NULL,
  monto numeric(14, 4) NOT NULL,
  esta_paga boolean NOT NULL DEFAULT false,
  fecha_pago timestamptz,
  fk_metodo_pago integer REFERENCES public.metodo_pago (id_metodo_pago),
  destinatario_nombre varchar(200) NOT NULL,
  destinatario_telefono varchar(32) NOT NULL,
  direccion_entrega text NOT NULL,
  fk_destinatario integer REFERENCES public.destinatario (id_destinatario) ON DELETE SET NULL,
  fk_direccion integer REFERENCES public.direccion (id_direccion) ON DELETE SET NULL,
  observaciones text,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT factura_numero_unique UNIQUE (numero),
  CONSTRAINT factura_monto_nonneg CHECK (monto >= 0),
  CONSTRAINT factura_pago_coherente CHECK (
    (esta_paga = false AND fecha_pago IS NULL)
    OR (esta_paga = true)
  )
);

CREATE INDEX IF NOT EXISTS idx_factura_fk_cliente ON public.factura (fk_cliente);
CREATE INDEX IF NOT EXISTS idx_factura_esta_paga ON public.factura (esta_paga);
CREATE INDEX IF NOT EXISTS idx_factura_fk_pedido ON public.factura (fk_pedido);
