export {
  ROL_ID_CLIENTE,
  ROL_ID_REPARTIDOR,
  ROL_ID_ADMINISTRADOR,
  ROL_ID_SUPERVISOR,
  ROL_CODIGO_CLIENTE,
  ROL_CODIGO_REPARTIDOR,
  ROL_CODIGO_ADMINISTRADOR,
  ROL_CODIGO_SUPERVISOR,
} from '../logistica/logistica-rol.constants';

export {
  TIPO_DOCUMENTO_ID_CEDULA as TIPO_DOCUMENTO_ID_REGISTRO,
  TIPO_DOCUMENTO_ID_CEDULA,
  TIPO_DOCUMENTO_ID_NIT,
  TIPO_DOCUMENTO_ID_PASAPORTE,
  TIPO_DOCUMENTO_ID_CEDULA_EXTRANJERIA,
  TIPO_DOCUMENTO_ID_TARJETA_IDENTIDAD,
  TIPO_DOCUMENTO_ID_PEP,
  TIPO_DOCUMENTO_ID_PPT,
} from '../logistica/logistica-tipo-documento.constants';
