/** Claves de `public.variable` (seed `database/15-seed-variables.sql`). */
export const VAR = {
  CRON_ASIGNAR_REPARTIDORES_ENABLED: 'CRON_ASIGNAR_REPARTIDORES_ENABLED',
  ASIGNACION_MAX_ENTREGAS_POR_REPARTIDOR_DIA: 'ASIGNACION_MAX_ENTREGAS_POR_REPARTIDOR_DIA',
  ASIGNACION_ROL_REPARTIDOR_ID: 'ASIGNACION_ROL_REPARTIDOR_ID',
  PEDIDO_ESTADO_INICIAL_ID: 'PEDIDO_ESTADO_INICIAL_ID',
  ASIGNACION_ESTADO_PEDIDO_ASIGNADO_ID: 'ASIGNACION_ESTADO_PEDIDO_ASIGNADO_ID',
  ASIGNACION_ESTADOS_PEDIDO_ELEGIBLES: 'ASIGNACION_ESTADOS_PEDIDO_ELEGIBLES',
  REPARTIDOR_PEDIDO_ESTADO_ASIGNADO_ID: 'REPARTIDOR_PEDIDO_ESTADO_ASIGNADO_ID',
  REPARTIDOR_PEDIDO_ESTADO_EN_CAMINO_ID: 'REPARTIDOR_PEDIDO_ESTADO_EN_CAMINO_ID',
  REPARTIDOR_PEDIDO_ESTADO_ENTREGADO_ID: 'REPARTIDOR_PEDIDO_ESTADO_ENTREGADO_ID',
  ASIGNACION_GEOCODING_NOMINATIM: 'ASIGNACION_GEOCODING_NOMINATIM',
  ASIGNACION_NOMINATIM_CONTACT_EMAIL: 'ASIGNACION_NOMINATIM_CONTACT_EMAIL',
  ASIGNACION_REPARTIDORES_HUBS: 'ASIGNACION_REPARTIDORES_HUBS',
  LIST_PEDIDOS_FECHA_TZ: 'LIST_PEDIDOS_FECHA_TZ',
  REGISTER_EMAIL_AUTO_CONFIRM: 'REGISTER_EMAIL_AUTO_CONFIRM',
} as const;

export type VariableKey = (typeof VAR)[keyof typeof VAR];
